config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root to: redirect("/sign_in")

  scope module: :proponents do
    scope module: :application do
      scope module: :controllers do
        resources :proponents do
          collection do
            get 'calculate_inss_discount'
          end
        end
      end
    end
  end

  scope module: :sessions do
    scope module: :application do
      scope module: :controllers do
        get 'sign_up', to: 'registrations#new'
        post 'sign_up', to: 'registrations#create'
        get 'sign_in', to: 'logins#new'
        post 'sign_in', to: 'logins#create'
        delete 'logout', to: 'logins#destroy'
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Credi-Shop</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= vite_client_tag %>
    <%= vite_typescript_tag "application" %>
    <%= vite_stylesheet_tag "application.scss" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" %>
  </head>
  <body>
    <div class="d-flex flex-column" style="height: 100vh;">
      <% if flash[:success] %>
        <div
          class="p-4 bg-success font-medium rounded-lg text-center text-white"
          id="notice"
        ><%= flash[:success] %></div>
      <% end %>
      <% if flash[:error] %>
        <div
          class="p-4 bg-danger font-medium rounded-lg text-center text-white"
          id="alert"
        ><%= flash[:error] %></div>
      <% end %>
      <nav class="navbar navbar-dark bg-dark shadow-sm p-4">
        <div class="container d-flex justify-content-between align-items-center">
          <%= link_to Sessions::Infrastructure::Models::Current.user ? proponents_path : root_path do %>
            <%= vite_image_tag "images/logo.png",
            style: "width: 150px; height: auto; margin-bottom: 15px;" %>
          <% end %>
          <% if Sessions::Infrastructure::Models::Current.user %>
            <%= button_to logout_path, method: :delete, class: "btn btn-primary" do %>
              <i class="fa fa-sign-out" style="margin-right: 2px"></i>
              Logout
            <% end %>
          <% end %>
        </div>
      </nav>
      <main class="flex-grow-1 p-5">
        <div class="container mt-3">
          <%= yield %>
        </div>
      </main>
      <footer
        class="
          p-4 bg-dark d-flex justify-content-end align-items-center text-white
        "
      >
        <p>
          Desenvolvido com
          <i class="fa fa-heart text-danger" style="margin: 0 2px;"></i>
          por
          <span style="font-weight: bold">Lucas Alves</span>
        </p>
      </footer>
    </div>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" %>
  </body>
</html>

app/views/proponents/_form.html.erb
<div data-controller="proponent-form">
  <%= simple_form_for @proponent, url: locals[:url], html: { class: 'form-horizontal' }  do |f| %>
    <fieldset>
      <legend>Proponente</legend>
      <div class="form-group row mb-3">
        <div class="col-sm-6">
          <%= f.input :name,
                  input_html: {
                    class:
                      "form-control #{@proponent.errors[:name].any? ? "is-invalid" : ""}",
                    placeholder: "Nome",
                  } %>
          <% if @proponent.errors[:name].any? %>
            <p class="text-danger">
              <%= @proponent.errors[:name].first %>
            </p>
          <% end %>
        </div>
        <div class="col-sm-6">
          <%= f.input :cpf,
                  input_html: {
                    class:
                      "form-control #{@proponent.errors[:cpf].any? ? "is-invalid" : ""}",
                    placeholder: "CPF",
                    data: {
                      "proponent-form-target": "cpf",
                    },
                  } %>
          <% if @proponent.errors[:cpf].any? %>
            <p class="text-danger">
              <%= @proponent.errors[:cpf].first %>
            </p>
          <% end %>
        </div>
      </div>
      <div class="form-group row mb-3">
        <div class="col-sm-6">
          <%= f.label :date_of_birth, class: "mb-0" %>
          <%= f.date_field :date_of_birth,
                       class:
                         "form-control #{@proponent.errors[:date_of_birth].any? ? "is-invalid" : ""}",
                       placeholder: "Data de Nascimento" %>
          <% if @proponent.errors[:date_of_birth].any? %>
            <p class="text-danger">
              <%= @proponent.errors[:date_of_birth].first %>
            </p>
          <% end %>
        </div>
        <div class="col-sm-6">
          <%= f.input :salary,
                  input_html: {
                    class:
                      "form-control #{@proponent.errors[:salary].any? ? "is-invalid" : ""}",
                    placeholder: "Salário",
                    data: {
                      "proponent-form-target": "salary",
                      "proponent-id": @proponent.salary,
                    },
                  } %>
          <div class="text-warning" id="discount-salary"></div>
          <% if @proponent.errors[:salary].any? %>
            <p class="text-danger">
              <%= @proponent.errors[:salary].first %>
            </p>
          <% end %>
        </div>
      </div>
    </fieldset>
    <%= f.simple_fields_for :address do |address_fields| %>
      <fieldset class="mt-4">
        <legend>Endereço</legend>
        <div class="form-group row mb-3">
          <div class="col-sm-6">
            <%= address_fields.input :zipcode,
                                 input_html: {
                                   class:
                                     "form-control #{@proponent.address.errors[:zipcode].any? ? "is-invalid" : ""}",
                                   placeholder: "CEP",
                                   data: {
                                     action: "keyup->proponent-form#onCepChange",
                                     "proponent-form-target": "zipcode",
                                   },
                                 } %>
            <% if @proponent.address.errors[:zipcode].any? %>
              <p class="text-danger">
                <%= @proponent.address.errors[:zipcode].first %>
              </p>
            <% end %>
          </div>
          <div class="col-sm-6">
            <%= address_fields.input :street,
                                 input_html: {
                                   class:
                                     "form-control #{@proponent.address.errors[:street].any? ? "is-invalid" : ""}",
                                   placeholder: "Rua",
                                   data: {
                                     "proponent-form-target": "street",
                                   },
                                 } %>
            <% if @proponent.address.errors[:street].any? %>
              <p class="text-danger">
                <%= @proponent.address.errors[:street].first %>
              </p>
            <% end %>
          </div>
        </div>
        <div class="form-group row mb-3">
          <div class="col-sm-6">
            <%= address_fields.input :district,
                                 input_html: {
                                   class:
                                     "form-control #{@proponent.address.errors[:district].any? ? "is-invalid" : ""}",
                                   placeholder: "Bairro",
                                   data: {
                                     "proponent-form-target": "district",
                                   },
                                 } %>
            <% if @proponent.address.errors[:district].any? %>
              <p class="text-danger">
                <%= @proponent.address.errors[:district].first %>
              </p>
            <% end %>
          </div>
          <div class="col-sm-6">
            <%= address_fields.input :city,
                                 input_html: {
                                   class:
                                     "form-control #{@proponent.address.errors[:city].any? ? "is-invalid" : ""}",
                                   placeholder: "Cidade",
                                   data: {
                                     "proponent-form-target": "city",
                                   },
                                 } %>
            <% if @proponent.address.errors[:city].any? %>
              <p class="text-danger">
                <%= @proponent.address.errors[:city].first %>
              </p>
            <% end %>
          </div>
        </div>
        <div class="form-group row mb-3">
          <div class="col-sm-6">
            <%= address_fields.input :uf,
                                 input_html: {
                                   class:
                                     "form-control #{@proponent.address.errors[:uf].any? ? "is-invalid" : ""}",
                                   placeholder: "UF",
                                   data: {
                                     "proponent-form-target": "uf",
                                   },
                                 } %>
            <% if @proponent.address.errors[:uf].any? %>
              <p class="text-danger">
                <%= @proponent.address.errors[:uf].first %>
              </p>
            <% end %>
          </div>
          <div class="col-sm-6">
            <%= address_fields.input :number,
                                 input_html: {
                                   class:
                                     "form-control #{@proponent.address.errors[:number].any? ? "is-invalid" : ""}",
                                   placeholder: "Número",
                                 } %>
            <% if @proponent.address.errors[:number].any? %>
              <p class="text-danger">
                <%= @proponent.address.errors[:number].first %>
              </p>
            <% end %>
          </div>
        </div>
      </fieldset>
    <% end %>
    <%= f.simple_fields_for :phone do |phone_fields| %>
      <fieldset class="mt-4">
        <legend>Telefone</legend>
        <div class="form-group row mb-3">
          <div class="col-sm-6">
            <%= phone_fields.input :number,
                               input_html: {
                                 class:
                                   "form-control #{@proponent.phone.errors[:number].any? ? "is-invalid" : ""}",
                                 placeholder: "Número do telefone",
                                 data: {
                                   "proponent-form-target": "number",
                                 },
                               } %>
            <% if @proponent.phone.errors[:number].any? %>
              <p class="text-danger">
                <%= @proponent.phone.errors[:number].first %>
              </p>
            <% end %>
          </div>
          <div class="col-sm-6">
            <%= phone_fields.input :phone_type,
                               collection: [
                                 ["Pessoal", :personal],
                                 ["Referêncial", :reference],
                               ],
                               prompt: "Selecione o tipo do telefone",
                               input_html: {
                                 class:
                                   "form-control #{"is-invalid" if @proponent.phone.errors[:phone_type].any?}",
                               } %>
            <% if @proponent.phone.errors[:phone_type].any? %>
              <p class="text-danger">
                <%= @proponent.phone.errors[:phone_type].first %>
              </p>
            <% end %>
          </div>
        </div>
      </fieldset>
    <% end %>
    <div class="form-group row mt-3">
      <div class="col-sm-12 text-center">
        <%= f.button :submit, class: "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/proponents/_proponent.html.erb
<div class="card rounded">
  <div class="card-body">
    <h5 class="card-title mb-3"><%= proponent.name %></h5>
    <p class="text-secondary mb-1">
      <strong>CPF:</strong>
      <%= proponent.cpf %>
    </p>
    <p class="text-secondary mb-1">
      <strong>Data de Nascimento:</strong>
      <%= l(proponent.date_of_birth) %>
    </p>
    <p class="text-secondary mb-0">
      <strong>Salário:</strong>
      <%= "R$ #{number_to_currency(proponent.salary, unit: "", separator: ",", delimiter: ".")}" %>
    </p>
    <p class="text-secondary mb-0">
      <strong>CEP:</strong>
      <%= proponent.address.zipcode %>
    </p>
    <p class="text-secondary mb-0">
      <strong>Rua:</strong>
      <%= proponent.address.street %>
    </p>
    <p class="text-secondary mb-0">
      <strong>Número:</strong>
      <%= proponent.address.number %>
    </p>
    <p class="text-secondary mb-0">
      <strong>Bairro:</strong>
      <%= proponent.address.district %>
    </p>
    <p class="text-secondary mb-0">
      <strong>Cidade:</strong>
      <%= proponent.address.city %>
    </p>
    <p class="text-secondary mb-0">
      <strong>UF:</strong>
      <%= proponent.address.uf %>
    </p>
    <p class="text-secondary mb-0">
      <strong>Telefone:</strong>
      <%= proponent.phone.number %>
    </p>
    <p class="text-secondary mb-0">
      <strong>Tipo do telefone:</strong>
      <%= t("activerecord.attributes.phone.phone_type_enum.#{proponent.phone.phone_type}") %>
    </p>
    <div class="d-flex align-items-center justify-content-start mt-3 gap-2">
      <%= link_to edit_proponent_path(proponent.id), class: "btn btn-warning" do %>
        <i class="fa fa-edit" style="margin-right: 4px"></i>
        Editar
      <% end %>
      <%= button_to proponent_path(proponent), method: :delete, class: "btn btn-danger", style: "margin-right: 4px;", onclick: "return confirm('Tem certeza que deseja excluir este proponente?');" do %>
        <i class="fa fa-trash"></i>
        Deletar
      <% end %>
    </div>
  </div>
</div>

app/views/proponents/edit.html.erb
<h1 class="mb-4"><%= t("actions.edit", model: @proponent.name) %></h1>

<%= render "proponents/form", locals: { url: proponent_path } %>

<%= link_to proponents_path, class: 'btn btn-secondary' do %>
  <i class="fa fa-arrow-left" style="margin-right: 4px"></i>
  Voltar
<% end %>

app/views/proponents/index.html.erb
<div class="d-flex justify-content-between align-items-center mb-5">
  <h1>Lista de Proponentes</h1>
  <%= link_to new_proponent_path, class: "btn btn-outline-primary" do %>
    <i class="fa fa-plus" style="margin-right: 8px"></i>Novo Proponente
  <% end %>
</div>
<% if @proponents_by_salary_range.values.any? { |data| data[:proponents].any? } %>
  <div class="row">
    <div class="col-10">
      <% @proponents_by_salary_range.each_with_index do |(range_name, data), index| %>
        <% if data[:proponents].any? %>
          <h5><%= range_name %></h5>
          <p>Total de funcionários:
            <%= data[:total] %></p>
          <div class="row mb-1">
            <% data[:proponents].each do |proponent| %>
              <div class="col-md-4 mb-4">
                <%= render "proponents/proponent", proponent: proponent %>
              </div>
            <% end %>
          </div>
          <div class="mb-5">
            <%= paginate data[:proponents],
            theme: "twitter-bootstrap-4",
            param_name: "salary_range_#{index}" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-2">
      <div style="width:max-content">
        <canvas
          data-controller="proponent-chart"
          data-proponent-chart-chart-data-value="<%= @proponents_by_salary_range.to_json %>"
        >
        </canvas>
      </div>
    </div>
  </div>
<% else %>
  <p class="text-secondary text-center" style="font-size: 18px">
    Nenhum proponente foi encontrado.
  </p>
<% end %>

app/views/proponents/new.html.erb
<h1 class="mb-4"><%= t("actions.new", model: @proponent.model_name.human) %></h1>

<%= render "proponents/form", locals: { url: proponents_path } %>

<%= link_to proponents_path, class: 'btn btn-secondary' do %>
  <i class="fa fa-arrow-left" style="margin-right: 4px"></i>
  Voltar
<% end %>